### ISSUE TITLE
multiple optimal solutions

### ISSUE THREAD

**Issue by hamid89** [SCIP-Interfaces/PySCIPOpt#157] opened 2018-04-26 16:38 UTC
I have a problem of retrieving all feasible (my case optimal) solutions of MIPS.

As I followed the instruction given on SCIP webpage that retrieving all optimal solutions of a problem is a two way stage: that is first solve the problem through simple scip model call then take optimal value as right hand side of the constraint and constraint is the objective function being added to the original problem.

Predefined counter settings for the save count and before calling counter method call the function and set the values like this :"primePattern.setBoolParam("constraints/countsols/collect", True)" .

Now it keep on solving the problem(untill infeasibility reach) and giving all feasible solutions:
My problem is: I need to access all the solutions and from each solution the optimal solution of each variable which can be accessed through :
void SCIPgetCountedSparseSolutions (SCIP *scip, SCIP_VAR *** vars, int
*nvars, SPARSESOLUTION ***sols, int *nsols)
  (located in "cons_countsols.h")
as given on guide. 

But I couldn't access this function. Could you please explain how to call it and please let me know if something I have explained above went wrong.

It would be highly appreciated.

Thank you,

**Comment by mattmilten** [comment] 2018-04-27 09:39
This functionality is currently not available through PySCIPOpt, i.e., `SCIPgetCountedSparseSolutions()` is not interfaced. We would still miss the transformation from the sparse solution to the original problem space. Within SCIP this is only possible by *writing out* all collected solutions.

@fserra do you have an idea on how this could be implemented best?

**Comment by hamid89** [comment] 2018-05-30 17:06
Any other suggestion regarding retrieving multiple optimal using PySCIPopt.

**Comment by mattmilten** [comment] 2019-03-13 15:21
duplicate of #248

**Closed by mattmilten** 2019-03-13 15:21 UTC
