### ISSUE TITLE
Solution as negated constraint

### ISSUE THREAD

**Issue by ramabile** [SCIP-Interfaces/PySCIPOpt#186] opened 2018-06-22 12:28 UTC
Dear SCIP workers,
I wonder if there is a method to remove a solution from the search space, for instance as a negated constraint. I did not find it in PySCIPOpt... maybe there is a native way in SCIP I am not aware of.

To understand why I need it, I explain my problem.
I have a graph coloring program. Variables are binary that represent a color of (for instance) an edge: if the variable is 1, the color of that edge is switched on; if the variable is 0, the color of that edge is switched off.
Constraints of the program are for instance the uniqueness of an edge color (an edge cannot be both red and blue) or the ratio of edge colors surrounding a vertex.
I set up a cycle to find all the possible solutions of the program. After initializing the model and its constraints, a loop optimizes the model, "frees" it, and removes the new solution from the program for the next cycle.

For the moment being, I negate a solution the following way: the summation of the binary variables with value 1 (_i.e._ edges with those particular colors) must be lower than/equal to the number of edges minus 1.
```
quicksum([evars[e,c] for e,c in zip(edges,colors)]) <= nevars - 1
```

I have also a prototypical way to set a solution made of integer/continous variables as negated constraint.
```
quicksum([(v-solval)*(v-solval) for v,solval in zip(vs,solvals)]) >= delta
```
where `delta` is the step between the closest different solutions. (_e.g._ 1 for integers)

Still, I have got the feeling this should not be the proper way to do that...
Thanks!

**Comment by fserra** [comment] 2018-06-22 16:18
so there is this model.count() function that tell SCIP to count solutions. However, it handles continuous variables differently: it counts only integer solutions and if you would have, say, to different solutions with the same integer assignment, it would be count as 1. Here is more info: http://scip.zib.de/doc/html/COUNTER.php

However, I am not aware of any better method. In particular, for handling continuous variables, you would either need to do something like what you do or introduce a ton of new binaries I guess.

**Comment by mattmilten** [comment] 2019-03-13 15:21
duplicate of #248

**Closed by mattmilten** 2019-03-13 15:21 UTC
Labels: feature, question
