### ISSUE TITLE
Impossible to implement Branching rules

### ISSUE THREAD

**Issue by palmieri-anthony** [SCIP-Interfaces/PySCIPOpt#194] opened 2018-07-17 16:11 UTC
Hello,
I'm trying to implement a branching rule in python, however i think it is not possible yet since we cannot create new child node.
Issue #106 refers a possible solution however the GitHub branch is quite old and i would expect it to not work with the current release of scip.
Do you have any solution or maybe I missed something?
Many thanks!

**Comment by fserra** [comment] 2018-07-17 18:04
Hi 

You are right. That branch will not work and right now you cannot create children.

However, taking the stuff that you need from that branch should be complicated and you can extend the interface! I created a branch fs/branching-rules and put some of the methods for branching from the old branch. I haven't tested, but I guess it will work. You can try it and add any other method that you might need.

If you add more methods, please, open a pull request.

**Comment by andynuaa** [comment] 2018-10-22 11:58
@fserra Hi, I am also implementing branch and price follow the test_coloring example. After cloning your branch and add some necessary declaration (i.e. SCIP_VARDATA and SCIPvarGetData) in .pyd file, I ran python setup.py install. However, when using "getLPBranchCands" and "createChild" func, a segmentation error would always occur. I suppose the problem is caused by PY_SCIP_CALL(xxx....). Did you actually notice this situation and got some ideas in tackling it?

**Comment by fserra** [comment] 2018-10-22 12:29
Hi @andynuaa I haven't seen such problem. To debug you can use python setup.py install --debug but I think you have to use an scip compiled in debug mode (@mattmilten is this right?). You would have to compile SCIP in debug and then tell PySCIPOPT to use that one (SCIPOPTDIR=/path/to/install/debug/mode/scip python setup.py install --debug)

But, why did you need to SCIPvarGetData? This shouldn't be necessary.

**Comment by andynuaa** [comment] 2018-10-22 14:15
Thanks for your timely response @fserra ! After reruning setup.py(didn't declare these func or struct aforementioned) with your instruction, I got the following error message.
----------------------------------------------------------------------------
$ SCIPOPTDIR=/home/Downloads/scipoptsuite-6.0.0/scip/bin python setup.py install
Compiling src/pyscipopt/scip.pyx because it changed.
[1/1] Cythonizing src/pyscipopt/scip.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        cdef int npriolpcands
        PY_SCIP_CALL(SCIPgetLPBranchCands(self._scip, &vars, NULL, &lpcandsfrac, NULL, &npriolpcands, NULL))
        PyVars = []
        fracs = []
        for i in range(npriolpcands):
            PyVars.append(<Variable>SCIPvarGetData(vars[i]))
                                   ^
------------------------------------------------------------

src/pyscipopt/scip.pyx:2449:36: undeclared name not builtin: SCIPvarGetData

Error compiling Cython file:
------------------------------------------------------------
...
        cdef int npriolpcands
        PY_SCIP_CALL(SCIPgetLPBranchCands(self._scip, &vars, NULL, &lpcandsfrac, NULL, &npriolpcands, NULL))
        PyVars = []
        fracs = []
        for i in range(npriolpcands):
            PyVars.append(<Variable>SCIPvarGetData(vars[i]))
                                                      ^
------------------------------------------------------------

src/pyscipopt/scip.pyx:2449:55: Cannot convert 'SCIP_VAR *' to Python object
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    extensions = cythonize(extensions)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/pyscipopt/scip.pyx
--------------------------------------------------------------
Just are these errors that motivated me to declare SCIPvarGetData.
Because I wanna carry out Ryan/Foster branching rule, so the 2 funcs are necessary to me. Thanks again for all your warm help.

**Comment by fserra** [comment] 2018-10-22 14:27
oh, I see. I am so sorry. I forgot to remove that line. I fixed it now and pushed to the branch the fix. You shouldn't need SCIPvarGetData. That was an experiment that didn't work so well ;)

I didn't test it though, so let me know if there is another problem.

Anyway, functions for branching should be added soon to master, see #208

**Comment by andynuaa** [comment] 2018-10-22 15:45
Thanks again! Remaining parts seem works well in my instance. I will keep you informed with any other possible pits.

**Comment by andynuaa** [comment] 2018-11-10 09:07
Hi @fserra , another question rised when I tried to do benders decomposition by hand. As this is an iterative process, I supposed that I would add cuts to master problem and reoptimize it until converging. However, after calling 'addVar', SCIP return with an error **'SCIP: method cannot be called at this time in solution process!'**. So I suppose that SCIP may not support remodifying its Model after solving?

I understand that SCIP have supports for doing benders decomposition through **initBendersDefault**. But since my idea is to combine branch and price with benders decomposition(MP: branch and price, SP: column generation), the variables are not fully known so explicit use seems hard. Thus I dicided to handle this by hand. Do you think this idea is feasible within PyscipOpt or can you possibly provide some examples to utilize Benders Decomposition interfaces like SCIP official documentation? Thank you!

My idea actually comes from this paper  

> The Recoverable Robust Tail Assignment Problem(2014)

**Comment by fserra** [comment] 2018-11-10 09:41
Hi

I guess @stephenjmaher is the right person to ask about your Benders application and how to use it. In tests/test_benders.py there is a test, that I guess is more of an example, which can be used as an example I guess.

Anyway, to add a variable you have to free the transformed problem before, `model.freeTransform()`. Afterward, you can modify the model however you want.

**Comment by andynuaa** [comment] 2018-11-10 10:44
Thanks again for all your kindness, I used freeProb instead of freeTransform before. While it was eligible to add constraints/variables, I found many detailed problem for resolving Master problem (branch and price). So using the interface may be a better option. I mentioned the new example beforehand because I wanna to use Magnanti-Wong method for improvement and may need to define customized pareto-optimal cuts form, which is not covered in the example.

**Comment by jeng1234** [comment] 2018-11-15 07:49
Hello,

what is the progress on implementing own branching rules in python? Have the updates been made to the master?

**Comment by fserra** [comment] 2018-11-15 08:03
yes, it should be possible. have a look at test_branch_probing_lp for an idea on how to implement one.

If you are missing some more functions from the SCIP C-API, you can either add them yourself or let us know

**Comment by jeng1234** [comment] 2018-11-15 09:17
I have a problem with installing the new master:
I downloaded the master and ran the setup. Afterwards the test instances give the error 'pyscipopt.scip.Model' object has no attribute 'chgVarLbGlobal'. However chgVarLbGlobal is defined in the scip.pyx file.
What am I missing?

**Comment by fserra** [comment] 2018-11-15 09:59
I have no idea, does anything else fails?

**Comment by jeng1234** [comment] 2018-11-15 13:53
@fserra: Thank you very much for your quick replies!
I could solve the problem: The setup did not rewrite all files. I had to delete them manually before running the setup again.

**Comment by andynuaa** [comment] 2018-11-15 15:54
Thanks for your kindness! @stephenjmaher. So is there any available existing python codes for customized Benders Decomposition? As I am not sure there's a one-to-one correspondence in necessary functions(name, usage) between C++ and Python.

**Comment by stephenjmaher** [comment] 2018-11-15 16:12
@andynuaa Unfortunately there are no examples for a custom Benders' decomposition in python or C at this stage.

The names that I gave in https://github.com/SCIP-Interfaces/PySCIPOpt/issues/194#issuecomment-438196501 are the method names for the Benders' decomposition python class.

Similar to the way that you created your `Pricer` and `Branchrule`, you need to define a `BendersXyz` class with the appropriate class methods implemented (as I described previously). Then with your `BendersXyz` class call `includeBenders` when building your model.

**Comment by andynuaa** [comment] 2019-02-26 13:22
@fserra Hi, fserra. I am wondering if I can resolve a transformed model with variables generated in pricer plugin. The actual motivation for such demand is that I want to apply benders decomposition and add cuts to the solved model (with priced variables generated in the previous iteration) because Pyscipopt seems to have some inconvenience in applying customized benders cuts.  While the existing **freeTransformed** function will free all the variables generated during solving and leave only the original problem, I am wondering if there is such method enable me to solve the transformed models directly.

**Comment by stephenjmaher** [comment] 2019-02-26 13:49
The best way to achieve what you are trying is to store all variables that you generate. Then when you free the transformed problem, you can add the previously generated variables upon resolving the master problem.

The method that I use for this is to add the variables generated in previous solves to the master problem during the first call to the farkas and redcost functions of your pricer.

**Comment by stephenjmaher** [comment] 2019-02-26 13:50
You also make a good point, that it is not currently possible to write a custom Benders' cut plugin. This is something that should be updated in the next release.

**Comment by andynuaa** [comment] 2019-02-26 13:57
@stephenjmaher Thank you for the reply! Then I guess I need to store the constraint coefficients and objective values as well if there are some side constraints other than set partition constraints. I can't wait to see the next release!

**Comment by stephenjmaher** [comment] 2019-02-26 14:01
@andynuaa If custom Benders' cut plugins are something that you need and are willing to test out, I could put together the necessary classes for this in the next couple of weeks.

**Comment by andynuaa** [comment] 2019-02-27 01:20
@stephenjmaher Sure, I'd love to, thank you Maher!

**Comment by andynuaa** [comment] 2019-02-27 01:21
> @andynuaa If custom Benders' cut plugins are something that you need and are willing to test out, I could put together the necessary classes for this in the next couple of weeks.

Sure, I'd love to, thank you!

**Comment by stephenjmaher** [comment] 2019-03-15 12:01
All discussion related to custom Benders' decomposition cuts in PySCIPOpt has been moved to https://github.com/SCIP-Interfaces/PySCIPOpt/issues/263

**Closed** 2020-05-28 19:07 UTC
