### ISSUE TITLE
after redirecting output, problems can't be written to files

### ISSUE THREAD

**Issue by fserra** [SCIP-Interfaces/PySCIPOpt#384] opened 2020-06-02 11:49 UTC
When using PySCIPOpt with a jupyter notebook, if I do:
```python
from pyscipopt import Model

model = Model()
model.redirectOutput()
model.writeProblem("model.cip")
```
then the model appears in the notebook and the file `model.cip` is empty. Uses
```
SCIP version 7.0.0 [precision: 8 byte] [memory: block] [mode: optimized] [LP solver: SoPlex 5.0.0] [GitHash: 0bc4dc9c65]
Copyright (C) 2002-2020 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)
```

**Comment by mattmilten** [comment] 2020-06-02 18:29
Duplicate of #243

**Closed** 2020-06-02 18:29 UTC

**Comment by sobsobkmz** [comment] 2022-10-04 20:44
#384
