### ISSUE TITLE
about MinIISC application

### ISSUE THREAD

**Issue by feidapeng** [SCIP-Interfaces/PySCIPOpt#192] opened 2018-07-12 08:31 UTC
i see MinIISC is an application within SCIP.   but not in PySCIPOpt . Is there any plan to implement MinIISC ?  ToT

**Comment by mattmilten** [comment] 2018-07-12 09:34
PySCIPOpt only uses functionality from SCIP itself. Applications that extend the core functionality like MinIISC cannot be wrapped easily. We would need to move the MinIISC code into the main SCIP library. To the best of my knowledge there are no plans to do that yet. I does sound very reasonable, though, and I will try to find a solution.

**Comment by mattmilten** [comment] 2018-09-10 12:37
duplicate of #172

**Closed by mattmilten** 2018-09-10 12:37 UTC

**Comment by whille** [comment] 2020-11-04 01:50
could MiniISC solve MIP problem? 
I found:
ERROR: input file contains integer variables. The code only works for LPs.

**Comment by mattmilten** [comment] 2020-11-04 08:23
This is significantly harder to do for MIPs than for LPs and as far as I know not planned to be implemented anytime soon.
