### ISSUE TITLE
New to PySCIPOpt

### ISSUE THREAD

**Issue by spoudel285688** [SCIP-Interfaces/PySCIPOpt#121] opened 2018-02-01 22:03 UTC
Hi all,

I am new to python and trying to use SCIP for Mixed integer linear programming (MILP) with python interface. However, I am not able to build and solve a model as given in "https://github.com/SCIP-Interfaces/PySCIPOpt". I get following error everytime I run the code:

ImportError: DLL load failed: The specified module could not be found.

Any comments and suggestions will be appreciated.

Thanks
Shiva

**Comment by mattmilten** [comment] 2018-02-02 07:46
Did you follow the steps in [INSTALL](https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.rst)?
You need to be more precise and describe what you have done to trigger the error.

**Comment by mattmilten** [comment] 2018-02-02 07:50
possible duplicate of #36 and #102

**Comment by mattmilten** [comment] 2018-02-12 08:40
I'm closing this due to inactivity.

**Closed by mattmilten** 2018-02-12 08:40 UTC
Labels: installation, windows
